# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainwindow.ui'
#
# Created: Thu Aug 25 21:48:50 2011
#      by: PyQt4 UI code generator 4.8.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    _fromUtf8 = lambda s: s

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(809, 569)
        self.centralWidget = QtGui.QWidget(MainWindow)
        self.centralWidget.setObjectName(_fromUtf8("centralWidget"))
        self.horizontalLayout = QtGui.QHBoxLayout(self.centralWidget)
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.tabWidget = QtGui.QTabWidget(self.centralWidget)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.InputTab = QtGui.QWidget()
        self.InputTab.setObjectName(_fromUtf8("InputTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.InputTab)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.treeData = QtGui.QTreeWidget(self.InputTab)
        self.treeData.setContextMenuPolicy(QtCore.Qt.ActionsContextMenu)
        self.treeData.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.treeData.setTabKeyNavigation(True)
        self.treeData.setAlternatingRowColors(True)
        self.treeData.setSelectionMode(QtGui.QAbstractItemView.ExtendedSelection)
        self.treeData.setAnimated(True)
        self.treeData.setHeaderHidden(False)
        self.treeData.setColumnCount(1)
        self.treeData.setObjectName(_fromUtf8("treeData"))
        self.horizontalLayout_2.addWidget(self.treeData)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.tableCommonAttrs = QtGui.QTableWidget(self.InputTab)
        self.tableCommonAttrs.setAlternatingRowColors(True)
        self.tableCommonAttrs.setColumnCount(2)
        self.tableCommonAttrs.setObjectName(_fromUtf8("tableCommonAttrs"))
        self.tableCommonAttrs.setColumnCount(2)
        self.tableCommonAttrs.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableCommonAttrs.setHorizontalHeaderItem(0, item)
        item = QtGui.QTableWidgetItem()
        self.tableCommonAttrs.setHorizontalHeaderItem(1, item)
        self.tableCommonAttrs.horizontalHeader().setStretchLastSection(True)
        self.tableCommonAttrs.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableCommonAttrs)
        self.tableVariableAttrs = QtGui.QTableWidget(self.InputTab)
        self.tableVariableAttrs.setAlternatingRowColors(True)
        self.tableVariableAttrs.setWordWrap(False)
        self.tableVariableAttrs.setCornerButtonEnabled(True)
        self.tableVariableAttrs.setColumnCount(1)
        self.tableVariableAttrs.setObjectName(_fromUtf8("tableVariableAttrs"))
        self.tableVariableAttrs.setColumnCount(1)
        self.tableVariableAttrs.setRowCount(0)
        item = QtGui.QTableWidgetItem()
        self.tableVariableAttrs.setHorizontalHeaderItem(0, item)
        self.tableVariableAttrs.horizontalHeader().setStretchLastSection(True)
        self.tableVariableAttrs.verticalHeader().setStretchLastSection(False)
        self.verticalLayout.addWidget(self.tableVariableAttrs)
        self.horizontalLayout_2.addLayout(self.verticalLayout)
        self.tabWidget.addTab(self.InputTab, _fromUtf8(""))
        self.DataPlot = QtGui.QWidget()
        self.DataPlot.setObjectName(_fromUtf8("DataPlot"))
        self.tabWidget.addTab(self.DataPlot, _fromUtf8(""))
        self.FitTab = QtGui.QWidget()
        self.FitTab.setObjectName(_fromUtf8("FitTab"))
        self.fitFunc = QtGui.QTextEdit(self.FitTab)
        self.fitFunc.setGeometry(QtCore.QRect(20, 40, 451, 151))
        self.fitFunc.setObjectName(_fromUtf8("fitFunc"))
        self.startParams = QtGui.QLineEdit(self.FitTab)
        self.startParams.setGeometry(QtCore.QRect(20, 250, 261, 22))
        self.startParams.setObjectName(_fromUtf8("startParams"))
        self.label = QtGui.QLabel(self.FitTab)
        self.label.setGeometry(QtCore.QRect(20, 10, 114, 16))
        self.label.setObjectName(_fromUtf8("label"))
        self.label_2 = QtGui.QLabel(self.FitTab)
        self.label_2.setGeometry(QtCore.QRect(30, 230, 98, 16))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.xSelector = QtGui.QComboBox(self.FitTab)
        self.xSelector.setGeometry(QtCore.QRect(320, 250, 111, 26))
        self.xSelector.setObjectName(_fromUtf8("xSelector"))
        self.tabWidget.addTab(self.FitTab, _fromUtf8(""))
        self.horizontalLayout.addWidget(self.tabWidget)
        MainWindow.setCentralWidget(self.centralWidget)
        self.menuBar = QtGui.QMenuBar(MainWindow)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 809, 22))
        self.menuBar.setDefaultUp(True)
        self.menuBar.setNativeMenuBar(True)
        self.menuBar.setObjectName(_fromUtf8("menuBar"))
        self.menuFile = QtGui.QMenu(self.menuBar)
        self.menuFile.setObjectName(_fromUtf8("menuFile"))
        MainWindow.setMenuBar(self.menuBar)
        self.mainToolBar = QtGui.QToolBar(MainWindow)
        self.mainToolBar.setObjectName(_fromUtf8("mainToolBar"))
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.mainToolBar)
        self.statusBar = QtGui.QStatusBar(MainWindow)
        self.statusBar.setObjectName(_fromUtf8("statusBar"))
        MainWindow.setStatusBar(self.statusBar)
        self.loadFile = QtGui.QAction(MainWindow)
        self.loadFile.setObjectName(_fromUtf8("loadFile"))
        self.menuFile.addAction(self.loadFile)
        self.menuBar.addAction(self.menuFile.menuAction())

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtGui.QApplication.translate("MainWindow", "MainWindow", None, QtGui.QApplication.UnicodeUTF8))
        self.treeData.headerItem().setText(0, QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.tableCommonAttrs.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Common Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.tableCommonAttrs.horizontalHeaderItem(1).setText(QtGui.QApplication.translate("MainWindow", "Value", None, QtGui.QApplication.UnicodeUTF8))
        self.tableVariableAttrs.horizontalHeaderItem(0).setText(QtGui.QApplication.translate("MainWindow", "Variable", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.InputTab), QtGui.QApplication.translate("MainWindow", "Input", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.DataPlot), QtGui.QApplication.translate("MainWindow", "Data", None, QtGui.QApplication.UnicodeUTF8))
        self.label.setText(QtGui.QApplication.translate("MainWindow", "Fit function f(p,x):", None, QtGui.QApplication.UnicodeUTF8))
        self.label_2.setText(QtGui.QApplication.translate("MainWindow", "Start parameter", None, QtGui.QApplication.UnicodeUTF8))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.FitTab), QtGui.QApplication.translate("MainWindow", "Fit", None, QtGui.QApplication.UnicodeUTF8))
        self.menuFile.setTitle(QtGui.QApplication.translate("MainWindow", "File", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFile.setText(QtGui.QApplication.translate("MainWindow", "Load file", None, QtGui.QApplication.UnicodeUTF8))
        self.loadFile.setShortcut(QtGui.QApplication.translate("MainWindow", "Ctrl+L", None, QtGui.QApplication.UnicodeUTF8))

